In [2]:
# numpy set opreation
import numpy as np
a=np.array([1,1,1,2,3,4,5,5,6,7])
x=np.unique(a)
print(x)

[1 2 3 4 5 6 7]


In [3]:
# finding union
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
anan=(np.union1d(a,b))
print(anan)

[1 2 3 4 5 6]


In [4]:
# finding intyersection
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
anan=np.intersect1d(a,b,assume_unique=True)
print(anan)

[3 4]


In [5]:
# finding difference
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
anan=np.setdiff1d(a,b,assume_unique=True)
print(anan)

[1 2]


In [6]:
# finding symmetric difference
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
anan=np.setxor1d(a,b,assume_unique=True)
print(anan)

[1 2 5 6]


In [9]:
# element wise exponentiation
import numpy as np
a=np.array([1,2,3])
result1=a**2
print(result1)
result2=np.power(a,2)
print(result2)

[1 4 9]
[1 4 9]


In [12]:
import numpy as np
a=np.empty(10)
print(a)

[4.9e-324 4.9e-324 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 2.5e-323
 3.0e-323 3.5e-323]


In [14]:
import numpy as np
a=np.array([1,3,5,7,9,11])
b=np.reshape(a,(2,3))
c=np.transpose(b)
print(a)
print(b)
print(c)

[ 1  3  5  7  9 11]
[[ 1  3  5]
 [ 7  9 11]]
[[ 1  7]
 [ 3  9]
 [ 5 11]]


In [20]:
# mediam
import numpy as np
a=np.array([1,3,5,7,9,11,13,15,17,19])
result1=np.median(a)
print(result1)

10.0


In [19]:
# mean
import numpy as np
a=np.array([1,3,5,7,9,11,13,15,17,19])
r=np.mean(a)
print(r)

10.0


In [23]:
# percentile()
import numpy as np
a=np.array([1,3,5,7,9,11,13,15,17,19])
r=np.percentile(a,100)
print(r)

19.0
